name: ssb-room
image: debian-10-x64
min_size: 1gb
config:
  #cloud-config
  packages:
    - wget
  runcmd:
    - wget https://raw.githubusercontent.com/staltz/ssb-room/master/install.sh
    - bash install.sh
